Develop GitHub CI/CD pipeline (build Docker image)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,21 +30,22 @@ jobs:
           NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
 
       # Build and publish Docker image for packages/aisbreaker-server/
-      - name: Build Docker image, login and push to hub.docker.com
-        run: |
-          cd packages/aisbreaker-server/
+      #- name: Build Docker image, login and push to hub.docker.com
+      #  run: |
+      #    cd packages/aisbreaker-server/
 
-          export VERSION=`cat VERSION`
-          if [[ -z "$VERSION" ]] ; then
-            echo "Couldn't find valid VERSION file"
-            exit 1
-          fi
+      #    export VERSION=`cat VERSION`
+      #    if [[ -z "$VERSION" ]] ; then
+      #      echo "Couldn't find valid VERSION file"
+      #      exit 1
+      #    fi
 
-          docker build -t "aisbreaker/aisbreaker-server:${VERSION}" -t "aisbreaker/aisbreaker-server:latest" .
-          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
-          docker push --all-tags "aisbreaker/aisbreaker-server"
+      #    docker build -t "aisbreaker/aisbreaker-server:${VERSION}" -t "aisbreaker/aisbreaker-server:latest" .
+      #    docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
+      #    docker push --all-tags "aisbreaker/aisbreaker-server"
 
-  build-and-publish-docker-image:
+  build-and-publish-docker-image-aisbreaker-server:
+    # almost duplicated code - except env values
     runs-on: ubuntu-latest
     needs: build-and-publish-npm
     env:
@@ -56,7 +57,7 @@ jobs:
 
       - name: Build Docker image
         run: |
-          cd "${PACKAGE_DIR]}/"
+          cd "${PACKAGE_DIR}/"
 
           export VERSION=`cat VERSION`
           if [[ -z "$VERSION" ]] ; then
@@ -69,7 +70,39 @@ jobs:
 
       - name: Publish Docker image 
         run: |
-          cd packages/aisbreaker-server/
+          cd "${PACKAGE_DIR}/"
+
+          docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
+          docker push --all-tags "${IMAGE_NAME}"
+
+
+  build-and-publish-docker-image-aisbreaker-chat-webapp:
+    # almost duplicated code - except env values
+    runs-on: ubuntu-latest
+    needs: build-and-publish-npm
+    env:
+      PACKAGE_DIR: packages/aisbreaker-chat-webapp
+      IMAGE_NAME: aisbreaker/aisbreaker-chat-webapp
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Build Docker image
+        run: |
+          cd "${PACKAGE_DIR}/"
+
+          export VERSION=`cat VERSION`
+          if [[ -z "$VERSION" ]] ; then
+            echo "Couldn't find valid VERSION file"
+            exit 1
+          fi
+
+          cp ../../package-lock.json ./
+          docker build -t "${IMAGE_NAME}:${VERSION}" -t "${IMAGE_NAME}:latest" .
+
+      - name: Publish Docker image 
+        run: |
+          cd "${PACKAGE_DIR}/"
 
           docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
           docker push --all-tags "${IMAGE_NAME}"
